### ISSUE TITLE
Terrific memory leaks on remounting

### ISSUE THREAD

**Issue by vintlucky777** [MicheleBertoli/react-gmaps#29] opened 2015-12-11 10:18 UTC
## Memory leaks on frequently remounting components

In the case when we use a react-gmaps, say, in kind of "details-view" component, that will mount and unmount frequently, gmaps lead to huge memory leaks.

The good way would be to use a single instance of gmaps, accociated with DOM id of the parent element.

Moreover to that, to support hot-reloading, this instance can be stored in the `window` scope, and taken from there on component mount

**Comment by vintlucky777** [comment] 2015-12-11 10:19
I've actually already been solving an issue like that in a project of mine. But I used native gmaps js API.
Should I make a PR to fix this?

**Comment by MicheleBertoli** [comment] 2015-12-13 12:48
Hey @vintlucky777,
thank you very much for pointing the problem out.

Personally, I never had any memory-related problems with the maps in my apps but I heard a lot of people complaining about it.

If you could submit a PR it would be great, in the meanwhile I'll try to reproduce the problem.

Have a nice day!

**Comment by MicheleBertoli** [comment] 2015-12-13 13:34
Here we go:

<img width="1530" alt="screen shot 2015-12-13 at 13 29 27" src="https://cloud.githubusercontent.com/assets/1308971/11767202/d4a85cdc-a19d-11e5-9098-124e7d587799.png">
[source](https://gist.github.com/MicheleBertoli/75de5da8fd625b51c03c)

**Comment by MicheleBertoli** [comment] 2016-03-05 08:48
Any updates on this @vintlucky777?
Thanks!

**Comment by vintlucky777** [comment] 2016-03-05 08:51
@MicheleBertoli I still find the only solution to actually work is the one when you manually keep the references to gmaps DOM-node and try to reutilize it as much as possible.
I'll put up a PR for this one.

**Comment by dstockdale** [comment] 2016-03-23 04:57
Hi @vintlucky777 / @MicheleBertoli. Any progress with this issue? I've come up against this happening as well now. I'll go ahead and have a look at what the issue is but don't want to redo anything that's already been sorted out.

**Comment by MicheleBertoli** [comment] 2016-03-23 09:25
Hey @dstockdale, I'm really interested in fixing this as well. 
I was waiting for @vintlucky777 because he said he already got a solution.
If I won't receive any PR before Saturday, I'll fix it during the week-end.
Have a nice day!

**Comment by MicheleBertoli** [comment] 2016-03-28 16:34
Hello @dstockdale and @vintlucky777,
I spent a few hours working on the memory issue and I've got some pretty good results to share.

Running [this script](https://gist.github.com/MicheleBertoli/75de5da8fd625b51c03c) 100 times on the current master gives the following results:

<img width="722" alt="screen shot 2016-03-28 at 17 26 44" src="https://cloud.githubusercontent.com/assets/1308971/14082888/7589989a-f50a-11e5-9125-9a9070c97d0d.png">

While running it on the [memory-leak](https://github.com/MicheleBertoli/react-gmaps/tree/memory-leak) branch gives this:

<img width="729" alt="screen shot 2016-03-28 at 17 25 26" src="https://cloud.githubusercontent.com/assets/1308971/14082891/79dd779a-f50a-11e5-83cc-331435d72896.png">

I still want to clean everything up a little bit before merging and publishing the new version on `npm` but I'm pretty happy with the solution.
Feedbacks are welcome :)

**Comment by dstockdale** [comment] 2016-04-13 07:20
Hi @MicheleBertoli sorry I've been having a bit of a nightmare with a project going gnarly on me but looks good. I'll test it out tomorrow and let you know how what I was working on runs with it.

**Comment by MicheleBertoli** [comment] 2016-04-13 08:17
Thank you very much @dstockdale, you can install it with `npm i react-gmaps@rc`.
I'm now happy with the code and the memory leak is fixed.

The only problem is that when you recycle a previously created map, you get a map with all the options you applied before. For example, if you set a custom style or you hide some controls you are going to get a map with those styles and controls all the time.
I (partially) solved the problem applying the ["default" options](https://github.com/MicheleBertoli/react-gmaps/blob/memory-leak/src/utils/default-map-options.js) before reusing the map but if a user added some overlays directly on it (using `onMapCreated` instead of the lib's components) there's no way to clean them out.
That's the reason why I didn't merge it yet.

**Comment by sonsoleslp** [comment] 2017-07-27 21:39
Is this fixed in the master branch now?

**Comment by MicheleBertoli** [comment] 2017-07-28 08:52
Hello @sonsoleslp, this branch has never been merged because it needed proper testing and feedback, but please keep in mind that the "memory leaking" problem is due to the Google Maps SDK (not this package) and it happens only in some particular scenario (for example, it never happened to me - and I used this packaged in production).

**Comment by MicheleBertoli** [comment] 2017-10-08 07:31
Closing due to inactivity.

**Closed by MicheleBertoli** 2017-10-08 07:31 UTC
